### ISSUE TITLE
Upgrade to 5.2

### ISSUE THREAD

**Issue by isanai69** [socieboy/chat#1]
Having this Kind of error when using your php artisan chat:tables
Call to undefined method Illuminate\Foundation\Application::bindShared()

please reply thnx

**Comment by socieboy** [comment]
I did the forum for the version 5.0 and currently im not maintaining this repository.. sorry

**Comment by yash2code** [comment]
please upgrade!

**Comment by folkevil** [comment]
bindShared changed to singleton 
@yash2code @isanai69 you can update from bindShare to singleton in file Socieboy\Chat\ChatServiceProvider. And add Route:: in route.php
@socieboy thank you for your package, i'm trying to learn how vue and laravel work together. I'm looking for server script ( socket.js ? ) in your package but not found. 

Tried to run node chat.js but got error.
